import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/src/i18n/routing";
import { notFound } from "next/navigation";
import { getMessages, setRequestLocale } from "next-intl/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Definimos que 'params' es una Promesa que eventualmente nos dará el 'locale'.
type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

// 4. generateStaticParams:
// Esta función le dice a Next.js en tiempo de compilación qué idiomas existen.
// Esto permite que el sitio sea estático y súper rápido (SSG).
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

// 5. RootLayout (Componente Principal):
export default async function RootLayout({ children, params }: Props) {
  // A. Esperamos a que los parámetros de la URL se resuelvan.
  const { locale } = await params;

  // B. Validación de seguridad: si el idioma no está en la lista (en, es, de),
  // mostramos la página de error 404 inmediatamente.
  if (!hasLocale(routing.locales, locale)) return notFound();

  // C. setRequestLocale: Configura el idioma de la petición en el servidor.
  // Esto es crucial para el renderizado estático.
  setRequestLocale(locale);

  // D. getMessages: Carga los mensajes desde el JSON correspondiente (ej: es.json).
  const messages = await getMessages();

  return (
    // E. Seteamos el atributo 'lang' del HTML para accesibilidad y SEO.
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* F. Proveedor de Mensajes: Envuelve toda la app para que cualquier 
            componente hijo pueda usar t('HomePage.title') */}
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
